services:
  laravel.test:
    build:
      context: ./docker/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
        WWWUSER: "${WWWUSER}"
    image: sail-8.4/app
    user: root

    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
      ORACLE_PASSWORD: "${ORACLE_PASSWORD:-password}"

    volumes:
      - ".:/var/www/html"
    tty: true
    stdin_open: true
    command: sh -lc "tail -f /dev/null"

    networks:
      - sail
    depends_on:
      - oracle

  oracle:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "${ORACLE_HOST_PORT:-1522}:1521"
    environment:
      ORACLE_PASSWORD: "${ORACLE_PASSWORD:-password}"
      APP_USER: "${DB_USERNAME:-RAPRD}"
      APP_USER_PASSWORD: "${DB_PASSWORD:-password}"
    volumes:
      - "sail-oracle:/opt/oracle/oradata"
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-oracle:
    driver: local
